research_task:
  description: >
    Conduct a thorough research about {topic}
  expected_output: >
    A text for the writer to interpretate and write a summary text.
  agent: researcher

writing_task:
  description: >
    Review the text from the researcher and based on it must write the most insightful and feasible article about {topic}.
  expected_output: >
    A complete article about {topic} with max {words} words.
  agent: article_writer
